#!/usr/bin/env sh

# When spacebar icons are working
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# global settings
# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0x00775759
yabai -m config normal_window_border_color   0x00505050
yabai -m config insert_window_border_color   0xffd75f5f
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

# space config
yabai -m config --space 8 layout float

# rules for apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^App Store$"          manage=off
yabai -m rule --add app="^Activity Monitor$"   manage=off
yabai -m rule --add app="^Preview$"            manage=off
yabai -m rule --add app="^Bitwarden$"          manage=off
yabai -m rule --add app="^zoom.us$"            manage=off

yabai -m rule --add app="^Safari$"             space=^1
yabai -m rule --add app="^Brave$"              space=^1
yabai -m rule --add app="^kitty$"              space=^2
yabai -m rule --add app="^Telegram$"           space=^3
yabai -m rule --add app="^Spotify$"            space=^4


echo "yabai configuration loaded.."
