prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths: {}
theme:
  ui:
    table:
      showSeparator: true
  colors:
    text:
      primary: "#56949f" # foam
      secondary: "#d7827e" # rose
      inverted: "#907aa9" # iris
      faint: "#9893a5" # muted
      warning: "#ea9d34" # gold
      success: "#286983" #pine
    background:
      selected: "#faf4ed" # base
    border:
      primary: "#907aa9" # iris
      secondary: "#f4ede8" # highlight low
      faint: "#f4ede8" # highlight low
pager:
  diff: ""
confirmQuit: false
